### ISSUE TITLE
Can you provide a complete example?

### ISSUE THREAD

**Issue by EmbedXj** [dmarcous/dDBGSCAN#1]
The data format is not clear, and what is the result format. Thanks!

**Comment by dmarcous** [comment]
Hi Jesson, 
This project is still a work in progress (if you look at the code - most of the implementations are missing, and only the template exist).
I am working on it these days and expect to fully finish the project by the end of June (2018).
When I do finish the implementation, I will add a more complete example.
Leaving this open until I complete the tasks mentioned above.
Thanks for your interest and comment!

**Comment by EmbedXj** [comment]
Thanks for your reply!

**Comment by dmarcous** [comment]
See current Readme, the project is done in terms of functionality
